In [61]:
import numpy as np
import random

#巡回行列のサイズ
n=3

C=np.zeros((n,n),dtype=int)
for i in range(n):
    rand=random.randint(0, 9)
    for j in range(n):
        C[j][(i+j)%n]=rand

print('巡回行列C=')
print(C)

eig=np.linalg.eig(C)
print('固有値：')
print(eig[0])

巡回行列C=
[[6 4 3]
 [3 6 4]
 [4 3 6]]
固有値：
[13. +0.j         2.5+0.8660254j  2.5-0.8660254j]


In [67]:
import math
import cmath

theta=2*math.pi/n
P=np.zeros((n,n),dtype=complex)
P_inv=np.zeros((n,n),dtype=complex)
for i in range(n):
    for j in range(n):
        P[i][j]=cmath.rect(1, i*j*theta)
        P_inv[i][j]=cmath.rect(1, i*(n-j)*theta)/n
print('変換行列P=')
print(P)
print('Pの逆行列P^(-1)=')
print(P_inv)

変換行列P=
[[ 1. +0.j         1. +0.j         1. +0.j       ]
 [ 1. +0.j        -0.5+0.8660254j -0.5-0.8660254j]
 [ 1. +0.j        -0.5-0.8660254j -0.5+0.8660254j]]
Pの逆行列P^(-1)=
[[ 0.33333333+0.00000000e+00j  0.33333333+0.00000000e+00j
   0.33333333+0.00000000e+00j]
 [ 0.33333333-8.16431199e-17j -0.16666667-2.88675135e-01j
  -0.16666667+2.88675135e-01j]
 [ 0.33333333-1.63286240e-16j -0.16666667+2.88675135e-01j
  -0.16666667-2.88675135e-01j]]


In [69]:
P_inv@C@P

array([[ 1.30000000e+01+0.00000000e+00j, -8.88178420e-16+8.88178420e-16j,
         1.77635684e-15+2.66453526e-15j],
       [-1.11022302e-15+8.88178420e-16j,  2.50000000e+00+8.66025404e-01j,
        -2.22044605e-16+4.44089210e-16j],
       [ 1.44328993e-15+7.77156117e-16j,  2.22044605e-16+3.33066907e-16j,
         2.50000000e+00-8.66025404e-01j]])